[workspace]
members = [
    "data-layer",
    "preprocessing",
    "mechanisms",
    "privacy-accounting",
    "pipeline",
    "api",
    "examples",
]

resolver = "2"

[workspace.package]
edition = "2021"
authors = [""]
license = "MIT"
version = "0.1.0"
