[workspace]
members = [
    "data-layer",
    "preprocessing",
    "mechanisms",
    "privacy-accounting",
    "pipeline",
    "api",
    "examples",
]

resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Your Name <you@example.com>"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
